services:
  - type: static
    name: flowstate
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - source: /.*
        destination: /index.html
        type: rewrite
